# don't change these names unless you also do so elsewhere where they are
# explicitly referenced.

CHORD_LENGTH_ROOT = 17700
CHORD_LENGTH_WING_TIP = 4000
RATIO = CHORD_LENGTH_WING_TIP / CHORD_LENGTH_ROOT
OFFSET_WING_TIP = 42000
WING_TIP_TRANSLATION_X = 1000
WING_TIP_TRANSLATION_Y = 2000
WING_TIP_RELATIVE_ANGLE = 5

constants_length = {
    'CHORD_LENGTH_ROOT': CHORD_LENGTH_ROOT,
    'CHORD_LENGTH_WING_TIP': CHORD_LENGTH_WING_TIP,
    'OFFSET_WING_TIP': OFFSET_WING_TIP,
    'WING_TIP_TRANSLATION_X': WING_TIP_TRANSLATION_X,
    'WING_TIP_TRANSLATION_Y': WING_TIP_TRANSLATION_Y,
}

constants_angle = {
    'WING_TIP_RELATIVE_ANGLE': WING_TIP_RELATIVE_ANGLE,
}

constants_real = {
    'RATIO': RATIO
}
